### ISSUE TITLE
ValueError: not allowed to raise maximum limit

### ISSUE THREAD

**Issue by mary-0830** [Megvii-BaseDetection/DenseTeacher#1]
请问运行训练代码`pods_train --dir .`为什么会出现这个问题ValueError: not allowed to raise maximum limit呢？

**Comment by mary-0830** [comment]
注释掉就可以跑起来了

**Comment by ZRandomize** [comment]
没有遇到过这个问题，可以提供一下完整报错吗？

**Comment by mary-0830** [comment]
> 没有遇到过这个问题，可以提供一下完整报错吗？

我注释掉就可以了，不知道是不是线程被限制了

**Comment by ZRandomize** [comment]
如果可以提供稳定复现代码的话可以帮你查一下

**Comment by herfootsosmell** [comment]
> > 没有遇到过这个问题，可以提供一下完整报错吗？
> 
> 我注释掉就可以了，不知道是不是线程被限制了

您好 请问是在哪里注释掉，我也遇到了同样的问题
