### ISSUE TITLE
Question about unsup loss.

### ISSUE THREAD

**Issue by heiyuxiaokai** [Megvii-BaseDetection/DenseTeacher#12]
Here, teacher model and student model respectively adopt different data augment methods. And the strong one uses `random crop`, which will cause the change in object locations. I'm confused how `get_distill_loss` works while dense feature maps are not corresponding.
https://github.com/Megvii-BaseDetection/DenseTeacher/blob/ca5c29d04674fdb68c389839a2f8d9ec637ad4c9/coco-p10/runner.py#L242 https://github.com/Megvii-BaseDetection/DenseTeacher/blob/ca5c29d04674fdb68c389839a2f8d9ec637ad4c9/coco-p10/runner.py#L244 https://github.com/Megvii-BaseDetection/DenseTeacher/blob/ca5c29d04674fdb68c389839a2f8d9ec637ad4c9/coco-p10/runner.py#L321

**Comment by ZRandomize** [comment]
seem like your misunderstood the random crop. This augmentation replace a random patch of the image with pure noise, rather than replace the whole image with its patch.

**Comment by heiyuxiaokai** [comment]
> seem like your misunderstood the random crop. This augmentation replace a random patch of the image with pure noise, rather than replace the whole image with its patch.

Therefore, the output images of weak strong augmentation own the same object. I understand, and thanks.

**Comment by heiyuxiaokai** [comment]
Sorry to trouble you again. `RandomFlip` in `WeakAug` also cause the above situation.
https://github.com/Megvii-BaseDetection/DenseTeacher/blob/ca5c29d04674fdb68c389839a2f8d9ec637ad4c9/coco-p10/augmentations.py#L64

**Comment by ZRandomize** [comment]
In this code base, student model use StrongAug + Weak Aug while teacher use Weak Aug. Thus the geometric correspondence was retained.

**Comment by heiyuxiaokai** [comment]
> In this code base, student model use StrongAug + Weak Aug while teacher use Weak Aug. Thus the geometric correspondence was retained. see [here](https://github.com/Megvii-BaseDetection/DenseTeacher/blob/ca5c29d04674fdb68c389839a2f8d9ec637ad4c9/coco-p10/dataset.py#L127)

I see.
