### ISSUE TITLE
Could not get results in paper

### ISSUE THREAD

**Issue by fu-7** [Megvii-BaseDetection/DenseTeacher#18]
I run coco-p10 without modification and get AP33.11 which is much lower than 35.11 in paper. I want to know the reason.
By the way, when i check the code in runner.py get_distill_loss:
loss_deltas = (iou_loss(
            student_deltas[b_mask],
            teacher_deltas[b_mask],
            box_mode="ltrb",
            loss_type='giou',
            reduction="none",
        ) * teacher_quality[b_mask]).mean()
Here why is teacher_quality[b_mask] not teacher_quality[b_mask].sigmoid()? It is supposed to represent probability so why not use sigmoid?

**Comment by ZRandomize** [comment]
please check whether you are evaluating the TEACHER model, 33.11 mAP looks like the performance of the student. The second question is a bug, the code is removed in latest code and seems like it won't affect final performance..

**Comment by fu-7** [comment]
Thanks for your reply, the performance of teacher model is 35. Since i get the performance by using "tensorboard --logdir=output". Does the events of tensorboard save the performance of student model？

**Comment by ZRandomize** [comment]
yes, you can modify the "self._last_eval_results" [here](https://github.com/Megvii-BaseDetection/DenseTeacher/blob/64cf95ac3d296191c988a9c8b8d2a6b85a03b475/coco-p10/runner.py#L136) to choose which result to show in tensorboard
