### ISSUE TITLE
how can you know a anchor/sample is negative or positive?

### ISSUE THREAD

**Issue by chenslcool** [Megvii-BaseDetection/DenseTeacher#2]
I your paper 4.4, you propose three method dealing with "Hard Negative Samples". however, ther's no gt box label in ssod, how can you determine a sample is negative or not?

**Comment by ZRandomize** [comment]
Please kindly check the footprint:

> Since the “unlabeled images” under the COCO-Standard setting actually come with annotations, we can perform label assignments on images using these annotations. The difference between our division (k = 1) and the assigned foreground is defined as hard negatives

**Comment by chenslcool** [comment]
I got you. Thanks.
