### ISSUE TITLE
what is the function of the file coco_supervision.txt? i want to train own datastet, need i generate the same file.

### ISSUE THREAD

**Issue by liuhaolinwen** [Megvii-BaseDetection/DenseTeacher#21]
i don't konw the function of the coco_supervision.txt, i want to train own datastet, need i generate the same file, what should i do?

**Comment by ZRandomize** [comment]
This file is used in dataset division [here](https://github.com/Megvii-BaseDetection/DenseTeacher/blob/64cf95ac3d296191c988a9c8b8d2a6b85a03b475/coco-p10/dataset.py#L62). It distinguish an COCO image belongs to supervised set or unsupervised set.
If you are using your own data, please refer to [this](https://github.com/Megvii-BaseDetection/DenseTeacher/issues/8) issue.

**Comment by liuhaolinwen** [comment]
How to generate coco_supervision file? do you have any script?

**Comment by liuhaolinwen** [comment]
How to generate coco_supervision file? do you have any script?

**Comment by ZRandomize** [comment]
no, this is copied from unbiased teacher. You can simply generate it using:
size=len(dataset)
labeled_idx=np.random.choice(size,int(size*split_percentage/100),replace=False)
unlabeled_idx=list(set(range(size)) - set(labeled_idx))
