### ISSUE TITLE
student和teacher不同数据增强的疑问

### ISSUE THREAD

**Issue by 1224wxwx** [Megvii-BaseDetection/DenseTeacher#22]
作者您好，感谢分享优秀的工作，给了我很多启发。

    这两天正在仔细看论文域代码，但是产生了疑问，烦请帮忙解答：
student的图片经过强数据增强，和teacher的弱数据增强并不对应——比如student的图片经过RandCrop后只包含图片的一部分，预测出来的dense预测结果肯定也只包含了这一部分，与teacher预测出来的dense预测结果就无法匹配上了。
    即使把teacher的dense预测结果按照student做一样的数据增强的变化（比如把结果按照RandCrop后只取一部分），那teacher的预测结果也会比student少了很多，因为对于teacher来说先当于只取了一部分结果，仍然没法对应上。

    烦请作者帮忙解惑，在这种增强不同情况下，是如何匹配teacher的伪框和student的预测的。

**Comment by ZRandomize** [comment]
请注意，teacher使用weak aug，而student使用weak aug+strong aug。而在weak aug中不包含任何涉及几何的变换，也就是不包含crop、flip、jitter之类的操作。因此他们的logits依然具有对应关系

**Comment by 1224wxwx** [comment]
> 请注意，teacher使用weak aug，而student使用weak aug+strong aug。而在weak aug中不包含任何涉及几何的变换，也就是不包含crop、flip、jitter之类的操作。因此他们的logits依然具有对应关系

明白了，感谢！
