### ISSUE TITLE
你好，请问可否解答一下这个问题？

### ISSUE THREAD

**Issue by wyy-tcz** [Megvii-BaseDetection/DenseTeacher#25]
![c315c7ada9343d6a3dd5947e5ae0a3a](https://user-images.githubusercontent.com/72901243/206080009-97543539-6fd3-45b2-927e-154847351f0e.png)
ni你好，这个错误请问是找不到R-50.pkl文件吗？你有遇到过这种问题吗

**Comment by ZRandomize** [comment]
你好！这是megfile的版本导致的问题，可以先使用megfile==0.1.2

**Comment by wyy-tcz** [comment]
好的，谢谢您~还有一个问题，我按照cvpods项目里datasets文件里的readme准备了coco数据集，readme文件里说的{train,val}2017指的是train2017和val2017这两个文件吗？我都放进去了，但是现在老是报No such file or directory: '/root/exec/cvpods/datasets/coco/train2017/000000215565.jpg错，想问下是我的数据集有问题吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Megvii-BaseDetection/DenseTeacher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月7日(星期三) 下午2:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Megvii-BaseDetection/DenseTeacher] 你好，请问可否解答一下这个问题？ (Issue #25)





 
你好！这是megfile的版本导致的问题，可以先使用megfile==0.1.2

**Comment by ZRandomize** [comment]
train2017和val2017应当是两个文件夹，结构类似：
![image](https://user-images.githubusercontent.com/49480962/206118579-33e09968-6066-4cae-8bf0-4e3f369abd33.png)
是否是您忘记解压了呢

**Comment by wyy-tcz** [comment]
我看到，您的这个train2017和annotations是并列的文件夹哈？我把train2017放在annotations下了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Megvii-BaseDetection/DenseTeacher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月7日(星期三) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Megvii-BaseDetection/DenseTeacher] 你好，请问可否解答一下这个问题？ (Issue #25)





 
train2017和val2017应当是两个文件夹，结构类似：
 
 是否是您忘记解压了呢

**Comment by ZRandomize** [comment]
是的，应该是并列的

**Comment by wyy-tcz** [comment]
谢谢您。再打扰您一下，我这个一直报CUDA out of memory. Tried to allocate 252.00 MiB (GPU 0; 15.78 GiB total capacity; 683.08 MiB already allocated; 128.19 MiB free;这个错，我修改了Dense_teacher的coco-p10里的config.py里的&nbsp;IMS_PER_BATCH为4，还有cvpods里的engine/set up.py里的&nbsp;assert base_world_size，没有用。还有一种方法，用这个torch.cuda.empty_cache()清理内存，您知道应该在哪里改吗？或者是还应该改动哪里呢~~麻烦您啦


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Megvii-BaseDetection/DenseTeacher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月7日(星期三) 下午3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Megvii-BaseDetection/DenseTeacher] 你好，请问可否解答一下这个问题？ (Issue #25)





 
是的，应该是并列的

**Comment by ZRandomize** [comment]
如果需要修改batchsize，可能还需要同时修改IMS_PER_DEVICE，如batchsize减半：
IMS_PER_BATCH=8 #from 16
IMS_PER_DEVICE=1 #from 2

empty_cache我似乎没有手动调用过。
