### ISSUE TITLE
Denseteacher in YOLOX and other YOLOseries

### ISSUE THREAD

**Issue by wjm202** [Megvii-BaseDetection/DenseTeacher#27]
Thank you for your work！Have you tried Denseteacher in YoloX？
I want to try to migrate denseteacher to anchor free YOLO like YOLOX , but the effect is not ideal.Do you have any suggestions？

**Comment by ZRandomize** [comment]
Can you please offer some extra info about your implementation? We found DenseTeacher effective with methods like ATSS/OTA, also anchor based method RetinaNet.

**Comment by wjm202** [comment]
We try to use the denseteacher structure to semi-supervision yolo. Unsuploss only uses reg and cls, but only achieves 2.1 mAP improvement on 10% data，using unbiased v1 on yolo only 1.9mAP  improvement.However, ATSS and OTA are essentially based on the improvement of FCOS. I found that no article mentioned the semi supervised method on yolo.
