### ISSUE TITLE
Using a different dataset, how to reset NUM_CLASSES?

### ISSUE THREAD

**Issue by BroenLin** [Megvii-BaseDetection/DenseTeacher#29]
I am using a new dataset(not coco or voc) and the num_classes is 20 for my dataset instead of 80 for coco. I already changed num_classes in fcos.py. Yet, the config while training still shows that my model num_classes equals 80.
![config](https://user-images.githubusercontent.com/102841364/218291477-a931b402-90e7-4a81-88a9-95b7d20f7583.jpg)
![fcos](https://user-images.githubusercontent.com/102841364/218291478-28939376-5b27-4e41-be15-b95208a1bc7c.jpg)
plz help me.

**Comment by ZRandomize** [comment]
hi, please specify num_classes by insert "NUM_CLASSES=20" at [here](https://github.com/Megvii-BaseDetection/DenseTeacher/blob/8fbf465c38d43cacad0191ebd30ca5def824086b/coco-p10/config.py#L29), i.e., MODEL.FCOS.NUM_CLASSES=20

**Comment by BroenLin** [comment]
> hi, please specify num_classes by insert "NUM_CLASSES=20" at [here](https://github.com/Megvii-BaseDetection/DenseTeacher/blob/8fbf465c38d43cacad0191ebd30ca5def824086b/coco-p10/config.py#L29), i.e., MODEL.FCOS.NUM_CLASSES=20

It works. Thanks a lot.
