### ISSUE TITLE
在用一个新的数据集。如何改变num_classes?

### ISSUE THREAD

**Issue by BroenLin** [Megvii-BaseDetection/DenseTeacher#30]
我在用一个遥感数据集，num_classes只有20，但是config设置里num_classes是80，对应coco数据集，请问如何更改。我已经对fcos.py进行了更改，但是不起作用。训练时的config仍然是80。虽然可以训练到model_iter_0200000.pth，但是仍旧因为category_id=56而报错。
![fcos](https://user-images.githubusercontent.com/102841364/218291586-10777947-b8fe-4f46-87c2-ebc106692cca.jpg)

![config](https://user-images.githubusercontent.com/102841364/218291584-04d6d5d1-e9f1-4d49-bcb8-d47c38338782.jpg)

**Comment by ZRandomize** [comment]
请更改config.py，而不是直接更改code
