### ISSUE TITLE
Where is the implementations for selecting pixels with top k% score?

### ISSUE THREAD

**Issue by HyunjiEllenPak** [Megvii-BaseDetection/DenseTeacher#34]
Hi, I read your paper and I think the author suggests a simple and efficient strategy for semi-supervised object detection.
So I'm figuring out your implementation before experiments on my custom dataset and already read the issue(#19 ).

1. But I could't find the implementation which selects pixels with top k% score for suppressing low scoring predictions. 
Could you let me know which file has the implementation?

2. And the paper also experimented the three different strategies to deal with hard negative regions, including "suppressing", "ignoring" and "selecting". Do your implementation include those three options? where could I change the option?

Thank you.

**Comment by HyunjiEllenPak** [comment]
I resolved.

**Comment by clanguagesh** [comment]
can you tell me where you find it
