### ISSUE TITLE
problem about regression branch

### ISSUE THREAD

**Issue by fyting** [Megvii-BaseDetection/DenseTeacher#5]
Hi, thank you for your excellent work. Can you share details about how to do unsupervised learning for regression branch?

**Comment by ZRandomize** [comment]
The learning of regression branch is by default turned on and the weight is 1.
See [here](https://github.com/Megvii-BaseDetection/DenseTeacher/blob/ca5c29d04674fdb68c389839a2f8d9ec637ad4c9/coco-p10/config.py#L85)
Or you can find description in the [paper](https://arxiv.org/pdf/2207.02541.pdf) Sec. 4.4 Regression Branch

**Comment by Joker316701882** [comment]
Since there is no further response from the questioner, this issue is closed for now. Reopen it when necessary.
