### ISSUE TITLE
question about position regression consistency

### ISSUE THREAD

**Issue by JayYangSS** [Megvii-BaseDetection/DenseTeacher#6]
I found that there is no difference data augmentation related to coordinate transformation in your code， student model and teacher model use the same coordinate transfrom, so the consistency constraint supervision of position prediction may not be enough. Have you done any relevant experiments?

**Comment by Joker316701882** [comment]
@JayYangSS The inputs for the student model and the teacher model are different, they are still forced to produce the same outputs. This is the ''consistency constraint'' for the regression.

The geometrical augmentation may improve the performance, but we didn't try it. You can implement it by yourself and let us know if it works.

**Comment by Joker316701882** [comment]
Since there is no further response from the questioner, this issue is closed for now. Reopen it when necessary.
