### ISSUE TITLE
How can I organize and train my own datasets?

### ISSUE THREAD

**Issue by heiyuxiaokai** [Megvii-BaseDetection/DenseTeacher#8]
I would appreciate if you could provide some examples.

**Comment by ZRandomize** [comment]
the example of using existing datasets in CVPods is [here](https://github.com/Megvii-BaseDetection/DenseTeacher/blob/main/coco-p10/dataset.py#L75)
if you want to use your own datasets, please construct your dataset in form of:
`
class YourDataSet:
    def __init__(self, arg1, arg2):
        do_init()
        self.dataset_dicts=[items1,items2...]
`
like [this](https://github.com/Megvii-BaseDetection/DenseTeacher/blob/main/coco-p10/dataset.py#L18)
and use it like in [here](https://github.com/Megvii-BaseDetection/DenseTeacher/blob/main/coco-p10/config.py#L8)

**Comment by heiyuxiaokai** [comment]
> the example of using existing datasets in CVPods is [here](https://github.com/Megvii-BaseDetection/DenseTeacher/blob/main/coco-p10/dataset.py#L75) if you want to use your own datasets, please construct your dataset like [this](https://github.com/Megvii-BaseDetection/DenseTeacher/blob/main/coco-p10/dataset.py#L18) and use it like in [here](https://github.com/Megvii-BaseDetection/DenseTeacher/blob/main/coco-p10/config.py#L8)

Thank you for explaining~
